# Generated by Django 4.1.13 on 2023-12-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
