# Generated by Django 4.2.6 on 2023-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_contact_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_asigned_to_engineer',
            new_name='is_assigned_to_engineer',
        ),
    ]
