# Generated by Django 4.2.6 on 2023-10-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_is_asigned_to_engineer_ticket_is_assigned_to_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
